site_name: climan
theme:
  name: material
  icon:
    logo: octicons/file-binary-24
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
nav:
  - Quickstart: index.md
  - Install:  install.md
  - Usage: usage.md
  - Tools: tools.md
  - Uninstall: uninstall.md
  - Contribute: contribute.md

repo_name: ghokun/climan
repo_url: https://github.com/ghokun/climan
edit_uri: https://github.com/ghokun/climan-runner/edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ghokun
      name: ghokun on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ghokun
      name: ghokun on Twitter

copyright: ghokun - MIT Licence
