# Project information
site_name: climan
site_url: https://climan.dev
site_author: ghokun
site_description: cli manager for cloud native technologies

# Repository
repo_name: ghokun/climan
repo_url: https://github.com/ghokun/climan
edit_uri: https://github.com/ghokun/climan-runner/edit/main/docs/

# Copyright
copyright: MIT Licence

# Configuration
theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.instant
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: octicons/file-binary-24
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ghokun
      name: ghokun on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ghokun
      name: ghokun on Twitter

# Page tree
nav:
  - Quickstart: index.md
  - Install:  install.md
  - Usage: usage.md
  - Tools: tools.md
  - Uninstall: uninstall.md
  - Contribute: contribute.md
