name: Generate gh-pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tools-page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Climan list
        run: |
          curl -OL https://github.com/ghokun/climan/releases/latest/download/climan-linux-amd64
          mv climan-linux-amd64 climan
          chmod +x climan
          echo '```' > ./docs/tools.md; ./climan list >> ./docs/tools.md; echo '```' >> ./docs/tools.md
          rm climan
      - name: Commit changes
        run: |
          git config --global user.name 'ghokun'
          git config --global user.email 'ghokun@users.noreply.github.com'
          git add .
          git commit -am "Actions commit" || echo "No changes to commit"
          git push
  mkdocs:
    needs: tools-page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
