name: Generate Indexes
on:
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * *"
jobs:
  generate-indexes:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate indexes
        run: go run main.go
      - name: Commit changes
        run: |
          git config --global user.name 'ghokun'
          git config --global user.email 'ghokun@users.noreply.github.com'
          git add .
          git commit -am "Actions commit" || echo "No changes to commit"
          git push
  mkdocs:
    needs: generate-indexes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git pull origin main
      - name: Setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
