name: Generate Tools
on:
  push:
    branch:
      - "main"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Actions Commit
        run: |
          go run main.go
          git config --global user.name 'ghokun'
          git config --global user.email 'ghokun@users.noreply.github.com'
          git commit -am "Actions commit"
          git push
